#pragma once

#include <string_view>

namespace App {static constexpr std::string_view stringCanvas{
R"(
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                      xxxxxxx                                                          xxxxxxxx xxxxx                                                       xxxx                                                   |
|                                xxxxxxxxxxxxxxxxxxx                                                    xxx           xxxxxxx                     xxxxxxxxxxxx               xxxx                                                   |
|                             xxxxx             xxxxxx                   xxxx xx x x xxxx               xx                   xx               xxxxxxxxxxxxxxxxxxx            xxxx                                                   |
|                            xxx                    xxx              xxxx          xxxxxxxx             xx                     x            xxx                 xx           xxxx                                                   |
|                           xx                       xx           xxx                 x   xx            xx                     x          xx                     xx          xxx                                                    |
|                          xx                         xxx        xx                         xx          xx                     x         xx                       xx         xxxx                                                   |
|                        xxx                          xxx        x                            xx        x                     xx       xxx                          x         xxx                                                   |
|                       xxx                            xx      xx                              xx       x                     x        x                            xx       xxxx                                                   |
|                       xxx                                   x                                 x       x                    x        xx                             xx      xxxx                                                   |
|                       xx                                    x                                  x      x                   xx        x                              xx      xxxx                                                   |
|                       xx                                   xx                                   x     x                  xx        xx                              xx      xxxx                                                   |
|                       xx                                   x                                    x     x               xxx          x                               xx      xxxx                                                   |
|                       xx                                   x                                    x     x          xxxxx             x                              xxx      x x                                                    |
|                       xx                                   x                                    x     xxxxxxxxxxxxxx x             x                              xxx      x xx                                                   |
|                       xx                                   x                                   xx     x               xx xxx       xx                            xxx       xxxx                                                   |
|                       xxx                                  x                                   x      x                    xxx      x                             xx       xxxx                                                   |
|                       xxx                                  xx                                  x      xx                     x      xx                           xxx       xxx x                                                  |
|                        xx                           xx      x                                xx       xx                     x       x                           xxx       x xxx                                                  |
|                         xx                         xxx       x                              xx        xx                     x       xxx                        xxx        xxxxx                                                  |
|                           xx                       xx         xx                           xx         xxx                    x         xx                      xxxx        xxxxx                                                  |
|                            xxx                   xxxx           x                         xx          xxx                    x          xx                   xxxxx         xxxxxxxxxxxx xxxxxx xxxx xxx                           |
|                             xxxxx               xxx              xx                    xxx            xxx                   x            xx                xxx xx          xxxxxxxxxxxxxxxxxxxxxxxxxxxx                           |
|                                xxxxxxxxxxxxxxxxxxx                xxx              xxxxx              xxx                xxx              xxx             xxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxx                           |
|                                    xxxxxxxxx                         xxxx xxxxxxxxx                   xxxxxxx xxxxxx xxxxx                   xxxxxxxxxxxxxxx                                                                      |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
)"
};}
